
install:
    cd ./bob/nix/ && nixos-anywhere -- --flake .#bob --generate-hardware-config nixos-generate-config ./hardware-configuration.nix --target-host root@$BOB

update:
    cd ./bob/nix/ && nix flake update && nixos-rebuild switch --use-remote-sudo --flake .#bob --target-host $BOB --build-host $BOB --verbose

update-compose:
    DOCKER_HOST="ssh://$BOB" docker compose --file ./bob/docker/docker-compose.yml up --build --remove-orphans --detach
    DOCKER_HOST="ssh://$BOB" docker compose --file ./bob/docker/docker-compose.yml logs -f

minecraft-console *args:
    DOCKER_HOST="ssh://$BOB" docker compose --file ./bob/docker/docker-compose.yml exec minecraft rcon-cli {{args}}

compose *args:
    cd ./bob/docker/ && DOCKER_HOST="ssh://$BOB" docker compose {{args}}

test-installation:
    nixos-anywhere -- --flake ./bob/nix#vm --vm-test


test-minecraft:
    docker compose --file ./bob/docker/docker-compose.yml up --build --remove-orphans --detach minecraft
    docker compose --file ./bob/docker/docker-compose.yml logs -f minecraft

test-minecraft-console *args:
    docker compose --file ./bob/docker/docker-compose.yml exec minecraft rcon-cli {{args}}

