export DOCKER_HOST := "ssh://homeassistant.riccardoisola.dev"
export COMPOSE_FILE := "compose.yml:compose.override.yml:compose.lan.yml"

[working-directory: "nix"]
install host:
    nixos-anywhere -- --flake .#comet --generate-hardware-config nixos-generate-config ./hardware-configuration.nix --target-host root@{{host}}

[working-directory: "nix"]
update: && rebuild
    nix flake update

[working-directory: "nix"]
rebuild:
    nixos-rebuild-ng switch --sudo --flake .#comet --target-host $COMET --build-host $COMET --verbose

[working-directory: "docker"]
update-compose:
    docker compose up --build --remove-orphans --detach
    docker compose stop teams
    docker compose logs -f

[working-directory: "../services/rpg"]
update-rpg: && update-compose
    nix develop --command uv run python main.py

[working-directory: "docker"]
compose *args:
    docker compose {{args}}

docker *args:
    docker {{args}}

[working-directory: "docker"]
regenerate-wireguard-config:
    docker compose down -v wireguard
    docker compose up --build --remove-orphans --detach wireguard

download-wireguard-config:
    docker run --rm -v wireguard:/data:ro alpine sh -c 'tar czf - /data/peer*/peer*.conf'

import-wireguard-config:
    docker run --rm -v wireguard:/data:ro alpine sh -c 'tar czf - /data/peer*/peer*.conf' | tar -xz --strip-components 2
    mv ./peer1.conf ./home.conf
    nmcli c delete home || true
    nmcli c import type wireguard file ./home.conf
    nmcli c down home
    nmcli c modify home connection.autoconnect false
    password attachment-rm Home home.conf || true
    password attachment-import Home home.conf ./home.conf
    rm home.conf

download-homeassistant-backup:
    docker run --rm -v homeassistant:/data:ro alpine sh -c 'tar czf - /data/backups'

