services:
  mexicanbonora:
    container_name: mexicanbonora
    restart: always
    environment:
      TOKEN: ${MEXICANBONORA_TOKEN}
    networks:
      - mexicanbonora

  mutechromecastads:
    container_name: mutechromecastads
    restart: always
    environment:
      CHROMECAST_HOST: ${MUTECHROMECASTADS_CHROMECAST_HOST}
    networks:
      - mutechromecastads

  rpg:
    container_name: rpg
    restart: always
    ports: []
    networks:
      - rpg

networks:
  mexicanbonora:
  mutechromecastads:
  rpg:
