include:
  - ../../services/mexicanbonora/compose.yml
  - ../../services/mutechromecastads/compose.yml
  - ../../services/jobs-notifier/compose.yml
  - ./cron/compose.yml

services:
  mqtt:
    image: docker.io/eclipse-mosquitto:latest
    container_name: mqtt
    command:
      - "/usr/sbin/mosquitto"
      - "-c"
      - "/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
    read_only: true
    restart: always
    networks:
      - homeassistant

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - SUBDOMAINS=rikyisola,rikyisola-homeassistant
      - TOKEN=${DUCKDNS_TOKEN}
    read_only: true
    restart: always
    tmpfs:
      - /run:exec
    networks:
      - duckdns

  caddy:
    build: ./caddy
    container_name: caddy
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
    read_only: true
    volumes:
      - caddy:/data
    networks:
      - homeassistant

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    volumes:
      - homeassistant:/config
    restart: always
    networks:
      - homeassistant

  porkbun-ddns:
    image: "mietzen/porkbun-ddns:latest"
    container_name: porkbun-ddns
    environment:
      DOMAIN: "riccardoisola.dev"
      SUBDOMAINS: "homeassistant"
      SECRETAPIKEY: "${PORKBUN_SECRET_KEY}"
      APIKEY: "pk1_b568c6e2d1133113c2810c3a87cb769e17ca898a0c6e60d85579deea9d4e9ba9"
    restart: always
    networks:
      - porkbun-ddns

  watchtower:
    image: docker.io/nickfedor/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: watchtower
    read_only: true
    restart: always
    networks:
      - watchtower

  telegram-notifier:
    image: docker.io/lorcas/docker-telegram-notifier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    read_only: true
    container_name: telegram-notifier
    networks:
      - telegram-notifier
    healthcheck:
      disable: true
    environment:
      - TELEGRAM_NOTIFIER_BOT_TOKEN
      - TELEGRAM_NOTIFIER_CHAT_ID

  autoheal:
    image: docker.io/willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    read_only: true
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AUTOHEAL_CONTAINER_LABEL: all

  teams:
    image: docker.io/barjola/microsoft-teams-keepalive:latest
    container_name: teams
    restart: "no"
    init: true
    networks:
      - teams
    volumes:
      - teams:/data/profile1
    tmpfs:
      - /run
    environment:
      APP_LANG: "en-US"
    ports:
      - "1144:1144"
    labels:
      - keep

volumes:
  homeassistant:
    name: homeassistant
  caddy:
    name: caddy
  teams:
    name: teams

networks:
  duckdns:
  homeassistant:
  watchtower:
  telegram-notifier:
  porkbun-ddns:
  teams:
