services:
  mexicanbonora:
    container_name: mexicanbonora
    restart: always
    environment:
      TOKEN: ${MEXICANBONORA_TOKEN}
    networks:
      - mexicanbonora

  mutechromecastads:
    container_name: mutechromecastads
    restart: always
    environment:
      CHROMECAST_HOST: ${MUTECHROMECASTADS_CHROMECAST_HOST}
    networks:
      - mutechromecastads

  jobs-notifier:
    container_name: jobs-notifier
    restart: no
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_NOTIFIER_BOT_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_NOTIFIER_CHAT_ID}"
    networks:
      - jobs-notifier

volumes:
  jobs:
    name: jobs

networks:
  mexicanbonora:
  mutechromecastads:
  jobs-notifier:
