
[working-directory: "nix"]
install host:
    nixos-anywhere -- --flake .#deck --generate-hardware-config nixos-generate-config ./hardware-configuration.nix --target-host root@{{host}}

[working-directory: "nix"]
update: && rebuild
    nix flake update

[working-directory: "nix"]
rebuild:
    nixos-rebuild switch --sudo --flake .#deck --target-host $DECK --build-host $DECK --verbose

[working-directory: "kodi"]
kodi-extensions:
    rsync -r ./plugin.program.wifi $DECK:~/.var/app/tv.kodi.Kodi/data/addons/

keys text:
    ssh deck.local hyprctl -i 0 dispatch sendshortcut ',{{text}},'

cleanup:
    ssh deck.local nix-collect-garbage -d
    ssh deck.local sudo nix-collect-garbage -d
    ssh deck.local nix-store --optimise
    ssh deck.local sudo nix-store --optimise
