export DECK := "deck.local"

[working-directory: "nix"]
install:
    nixos-anywhere -- --flake .#deck --generate-hardware-config nixos-generate-config ./hardware-configuration.nix --target-host root@$DECK

[working-directory: "nix"]
update:
    nix flake update && nixos-rebuild switch --sudo --flake .#deck --target-host $DECK --build-host $DECK --verbose

[working-directory: "nix"]
rebuild:
    nixos-rebuild switch --sudo --flake .#deck --target-host $DECK --build-host $DECK --verbose

[working-directory: "kodi"]
kodi-extensions:
    rsync -r ./plugin.program.wifi $DECK:~/.var/app/tv.kodi.Kodi/data/addons/

keys text:
    ssh deck.local hyprctl -i 0 dispatch sendshortcut ',{{text}},'
