export DOCKER_HOST := "ssh://riccardoisola.dev"

[working-directory: "nix"]
install:
    nixos-anywhere -- --flake .#hetzner --generate-hardware-config nixos-generate-config ./hardware-configuration.nix --target-host root@$HETZNER

[working-directory: "nix"]
update: && rebuild
    nix flake update

[working-directory: "nix"]
rebuild:
    nixos-rebuild switch --sudo --flake .#hetzner --target-host $HETZNER --build-host $HETZNER --verbose

ssh *args:
    ssh $HETZNER {{args}}

[working-directory: "docker"]
update-compose:
    docker compose up --build --remove-orphans --detach
    docker compose logs -f

[working-directory: "docker"]
compose *args:
    docker compose {{args}}

docker *args:
    docker {{args}}
