services:
  cron:
    build: .
    read_only: true
    init: true
    networks:
      - socket-proxy
    restart: always
    container_name: cron
    environment:
      TZ: "Europe/Rome"
      DOCKER_HOST: "tcp://socket-proxy:2375"
